
package uy.volando.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "VolandoWS", targetNamespace = "http://ws.volando.uy/", wsdlLocation = "http://localhost:9128/volando?wsdl")
public class VolandoWS
    extends Service
{

    private static final URL VOLANDOWS_WSDL_LOCATION;
    private static final WebServiceException VOLANDOWS_EXCEPTION;
    private static final QName VOLANDOWS_QNAME = new QName("http://ws.volando.uy/", "VolandoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/volando?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOLANDOWS_WSDL_LOCATION = url;
        VOLANDOWS_EXCEPTION = e;
    }

    public VolandoWS() {
        super(__getWsdlLocation(), VOLANDOWS_QNAME);
    }

    public VolandoWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOLANDOWS_QNAME, features);
    }

    public VolandoWS(URL wsdlLocation) {
        super(wsdlLocation, VOLANDOWS_QNAME);
    }

    public VolandoWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOLANDOWS_QNAME, features);
    }

    public VolandoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VolandoWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort() {
        return super.getPort(new QName("http://ws.volando.uy/", "WebServicesPort"), WebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.volando.uy/", "WebServicesPort"), WebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOLANDOWS_EXCEPTION!= null) {
            throw VOLANDOWS_EXCEPTION;
        }
        return VOLANDOWS_WSDL_LOCATION;
    }

}
