
package uy.volando.publicar;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://ws.volando.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param avatarBytes
     * @param clearPhoto
     * @param descripcion
     * @param emailSesion
     * @param nickSesion
     * @param nombre
     * @param sitioWeb
     * @return
     *     returns uy.volando.publicar.DataAerolinea
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/actualizarPerfilAerolineaRequest", output = "http://ws.volando.uy/WebServices/actualizarPerfilAerolineaResponse")
    public DataAerolinea actualizarPerfilAerolinea(
        @WebParam(name = "nickSesion", partName = "nickSesion")
        String nickSesion,
        @WebParam(name = "emailSesion", partName = "emailSesion")
        String emailSesion,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "sitioWeb", partName = "sitioWeb")
        String sitioWeb,
        @WebParam(name = "avatarBytes", partName = "avatarBytes")
        byte[] avatarBytes,
        @WebParam(name = "clearPhoto", partName = "clearPhoto")
        boolean clearPhoto);

    /**
     * 
     * @param apellido
     * @param avatarBytes
     * @param clearPhoto
     * @param emailSesion
     * @param fechaNac
     * @param nacionalidad
     * @param nickSesion
     * @param nombre
     * @param numDocumento
     * @param tipoDocumento
     * @return
     *     returns uy.volando.publicar.DataCliente
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/actualizarPerfilClienteRequest", output = "http://ws.volando.uy/WebServices/actualizarPerfilClienteResponse")
    public DataCliente actualizarPerfilCliente(
        @WebParam(name = "nickSesion", partName = "nickSesion")
        String nickSesion,
        @WebParam(name = "emailSesion", partName = "emailSesion")
        String emailSesion,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "nacionalidad", partName = "nacionalidad")
        String nacionalidad,
        @WebParam(name = "tipoDocumento", partName = "tipoDocumento")
        TipoDocumento tipoDocumento,
        @WebParam(name = "numDocumento", partName = "numDocumento")
        String numDocumento,
        @WebParam(name = "fechaNac", partName = "fechaNac")
        XMLGregorianCalendar fechaNac,
        @WebParam(name = "avatarBytes", partName = "avatarBytes")
        byte[] avatarBytes,
        @WebParam(name = "clearPhoto", partName = "clearPhoto")
        boolean clearPhoto);

    /**
     * 
     * @return
     *     returns uy.volando.publicar.DataPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarPaquetesRequest", output = "http://ws.volando.uy/WebServices/listarPaquetesResponse")
    public DataPaqueteArray listarPaquetes();

    /**
     * 
     * @param nombrePaquete
     * @return
     *     returns uy.volando.publicar.DataPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/verPaqueteRequest", output = "http://ws.volando.uy/WebServices/verPaqueteResponse")
    public DataPaquete verPaquete(
        @WebParam(name = "nombrePaquete", partName = "nombrePaquete")
        String nombrePaquete);

    /**
     * 
     * @return
     *     returns uy.volando.publicar.DataAerolineaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarAerolineasRequest", output = "http://ws.volando.uy/WebServices/listarAerolineasResponse")
    public DataAerolineaArray listarAerolineas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns uy.volando.publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/loguearUsuarioRequest", output = "http://ws.volando.uy/WebServices/loguearUsuarioResponse")
    public DataUsuario loguearUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns uy.volando.publicar.DataCategoriaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarCategoriasRequest", output = "http://ws.volando.uy/WebServices/listarCategoriasResponse")
    public DataCategoriaArray listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.volando.publicar.DataAerolinea
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/verInfoAerolineaRequest", output = "http://ws.volando.uy/WebServices/verInfoAerolineaResponse")
    public DataAerolinea verInfoAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.volando.publicar.DataCliente
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/verInfoClienteRequest", output = "http://ws.volando.uy/WebServices/verInfoClienteResponse")
    public DataCliente verInfoCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param nickname
     * @param nombre
     * @return
     *     returns uy.volando.publicar.DataVueloEspecificoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarVuelosRequest", output = "http://ws.volando.uy/WebServices/listarVuelosResponse")
    public DataVueloEspecificoArray listarVuelos(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre);

    /**
     * 
     * @param nickname
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/obtenerAvatarRequest", output = "http://ws.volando.uy/WebServices/obtenerAvatarResponse")
    public byte[] obtenerAvatar(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/pingRequest", output = "http://ws.volando.uy/WebServices/pingResponse")
    public String ping(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre);

    /**
     * 
     * @param nickname
     * @param pwdCurrent
     * @param pwdNew
     */
    @WebMethod
    @Action(input = "http://ws.volando.uy/WebServices/cambiarPasswordRequest", output = "http://ws.volando.uy/WebServices/cambiarPasswordResponse")
    public void cambiarPassword(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "pwdCurrent", partName = "pwdCurrent")
        String pwdCurrent,
        @WebParam(name = "pwdNew", partName = "pwdNew")
        String pwdNew);

    /**
     * 
     * @return
     *     returns uy.volando.publicar.DataCiudadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarCiudadesRequest", output = "http://ws.volando.uy/WebServices/listarCiudadesResponse")
    public DataCiudadArray listarCiudades();

    /**
     * 
     * @param nicknameAerolinea
     * @param rutaSel
     * @param vueloSel
     * @return
     *     returns uy.volando.publicar.DataReservaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarReservasRequest", output = "http://ws.volando.uy/WebServices/listarReservasResponse")
    public DataReservaArray listarReservas(
        @WebParam(name = "nicknameAerolinea", partName = "nicknameAerolinea")
        String nicknameAerolinea,
        @WebParam(name = "rutaSel", partName = "rutaSel")
        String rutaSel,
        @WebParam(name = "vueloSel", partName = "vueloSel")
        String vueloSel);

    /**
     * 
     * @param idReserva
     * @param nicknameAerolinea
     * @param rutaSel
     * @param vueloSel
     * @return
     *     returns uy.volando.publicar.DataReserva
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/buscarReservaRequest", output = "http://ws.volando.uy/WebServices/buscarReservaResponse")
    public DataReserva buscarReserva(
        @WebParam(name = "nicknameAerolinea", partName = "nicknameAerolinea")
        String nicknameAerolinea,
        @WebParam(name = "rutaSel", partName = "rutaSel")
        String rutaSel,
        @WebParam(name = "vueloSel", partName = "vueloSel")
        String vueloSel,
        @WebParam(name = "idReserva", partName = "idReserva")
        int idReserva);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.volando.uy/WebServices/registrarRutaRequest", output = "http://ws.volando.uy/WebServices/registrarRutaResponse")
    public void registrarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        DataRuta arg0);

    /**
     * 
     * @param nicknameAerolinea
     * @return
     *     returns uy.volando.publicar.DataRutaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/listarPorAerolineaRequest", output = "http://ws.volando.uy/WebServices/listarPorAerolineaResponse")
    public DataRutaArray listarPorAerolinea(
        @WebParam(name = "nicknameAerolinea", partName = "nicknameAerolinea")
        String nicknameAerolinea);

}
