
package uy.volando.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://ws.volando.uy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns uy.volando.publicar.DataAerolinea
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/verInfoAerolineaRequest", output = "http://ws.volando.uy/WebServices/verInfoAerolineaResponse")
    public DataAerolinea verInfoAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns uy.volando.publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/loguearUsuarioRequest", output = "http://ws.volando.uy/WebServices/loguearUsuarioResponse")
    public DataUsuario loguearUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/pingRequest", output = "http://ws.volando.uy/WebServices/pingResponse")
    public String ping(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre);

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.volando.publicar.DataCliente
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.volando.uy/WebServices/verInfoClienteRequest", output = "http://ws.volando.uy/WebServices/verInfoClienteResponse")
    public DataCliente verInfoCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
