
package Presentacion;

import Logica.DataUsuario;
import Logica.Fabrica;
import Logica.IControladorUsuario;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
	private IControladorUsuario ICU;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(550, 550);
        this.internalRU.setVisible(false);
        this.internalVerInfoUsuario.setVisible(false);
        
        //Inicialización
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getIControladorUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        internalRU = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        txtnombreUsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        cmdRegistroUsuario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        internalVerInfoUsuario = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        txtCIUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidoUsuario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalRU.setTitle("Registrar Usuario");
        internalRU.setVisible(true);
        internalRU.getContentPane().setLayout(null);

        jLabel1.setText("Ingrese Nombre");
        internalRU.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 104, 16);

        txtnombreUsu.setName(""); // NOI18N
        txtnombreUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreUsuActionPerformed(evt);
            }
        });
        internalRU.getContentPane().add(txtnombreUsu);
        txtnombreUsu.setBounds(120, 20, 213, 30);

        jLabel2.setText("Ingrese apellido");
        internalRU.getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 100, 16);
        internalRU.getContentPane().add(txtapellido);
        txtapellido.setBounds(120, 70, 213, 30);

        jLabel3.setText("Ingrese C.I.");
        internalRU.getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 100, 16);
        internalRU.getContentPane().add(txtCI);
        txtCI.setBounds(120, 120, 213, 30);

        cmdRegistroUsuario.setText("Registrar");
        cmdRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistroUsuarioActionPerformed(evt);
            }
        });
        internalRU.getContentPane().add(cmdRegistroUsuario);
        cmdRegistroUsuario.setBounds(254, 179, 90, 29);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        internalRU.getContentPane().add(jButton2);
        jButton2.setBounds(140, 180, 90, 29);

        getContentPane().add(internalRU);
        internalRU.setBounds(180, 210, 410, 284);

        internalVerInfoUsuario.setTitle("Ver información de Usuario");
        internalVerInfoUsuario.setVisible(true);
        internalVerInfoUsuario.getContentPane().setLayout(null);

        jLabel4.setText("Ingrese número de Cédula");
        jLabel4.setToolTipText("");
        internalVerInfoUsuario.getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 40, 170, 16);
        internalVerInfoUsuario.getContentPane().add(txtCIUsuario);
        txtCIUsuario.setBounds(190, 30, 95, 30);

        jLabel5.setText("Información de Usuario");
        internalVerInfoUsuario.getContentPane().add(jLabel5);
        jLabel5.setBounds(127, 98, 160, 16);

        jLabel6.setText("Nombre");
        internalVerInfoUsuario.getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 141, 50, 16);

        jLabel7.setText("Apellido");
        internalVerInfoUsuario.getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 50, 16);

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        internalVerInfoUsuario.getContentPane().add(txtNombreUsuario);
        txtNombreUsuario.setBounds(80, 140, 271, 30);

        txtApellidoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoUsuarioActionPerformed(evt);
            }
        });
        internalVerInfoUsuario.getContentPane().add(txtApellidoUsuario);
        txtApellidoUsuario.setBounds(80, 190, 271, 30);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        internalVerInfoUsuario.getContentPane().add(jButton3);
        jButton3.setBounds(310, 30, 80, 30);

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        internalVerInfoUsuario.getContentPane().add(jButton4);
        jButton4.setBounds(340, 240, 75, 29);

        getContentPane().add(internalVerInfoUsuario);
        internalVerInfoUsuario.setBounds(50, -70, 490, 370);

        jMenu1.setText("Sesión");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registros");

        jMenuItem1.setText("Registrar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jMenuItem2.setText("Ver información de Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.internalRU.setVisible(true);
        this.internalRU.setLocation(25, 25);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cmdRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistroUsuarioActionPerformed
        // TODO add your handling code here:
        
        //Obtengo datos de los controles Swing
        String nombreU = this.txtnombreUsu.getText();
        String apellidoU = this.txtapellido.getText();
        String ciU = this.txtCI.getText();
        
        //A través de mi interfaz registro a un nuevo usuario en mi Sistema
        ICU.registrarUsuario(nombreU, apellidoU, ciU);
        
        //Limpio el internal Frame
        this.txtnombreUsu.setText("");
        this.txtapellido.setText("");
        this.txtCI.setText("");
        this.internalRU.setVisible(false);
        
        //Muestro éxito de la operación
        JOptionPane.showMessageDialog(this, "El Usuario se ha creado con éxito", "Registrar Usuario", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_cmdRegistroUsuarioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    	this.internalVerInfoUsuario.setSize(450, 450);
    	this.internalVerInfoUsuario.setLocation(25, 25);
    	this.internalVerInfoUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtApellidoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.internalRU.setVisible(false);
        this.txtnombreUsu.setText("");
        this.txtapellido.setText("");
        this.txtCI.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (this.txtCIUsuario.getText().equals("")){
            this.txtCIUsuario.setText("Ingresar CI");
        }
        else{
                    
            DataUsuario du = ICU.verInfoUsuario(this.txtCIUsuario.getText());
            this.txtNombreUsuario.setText(du.getNombre());
            this.txtApellidoUsuario.setText(du.getApellido());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.internalVerInfoUsuario.setVisible(false);
        this.txtNombreUsuario.setText("");
        this.txtApellidoUsuario.setText("");
        this.txtCIUsuario.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtnombreUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdRegistroUsuario;
    private javax.swing.JInternalFrame internalRU;
    private javax.swing.JInternalFrame internalVerInfoUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField txtApellidoUsuario;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtCIUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombreUsu;
    // End of variables declaration//GEN-END:variables
}
